Init MVI with dummy bottom bar
levabond/OnlineCinema pull request #1
Opened 2024-03-11 05:03 UTC by levabond

Что сдалено:
- Добавлен Home модуль на MVI (подробнее почитать [можно в ноушене](https://www.notion.so/lionbond/SwiftUI-MVI-07e857fb999541dc8051cd1b5f55f145?pvs=4)) 
- Добавлен глупый пример Bottom Bar'а

2024-03-11 05:32 UTC, jonibekbekmuratov requested changes

2024-03-11 05:32 UTC, jonibekbekmuratov commented on OnlineCinema/OnlineCinema.xcodeproj/project.xcworkspace/xcuserdata/levbondarenko.xcuserdatad/UserInterfaceState.xcuserstate
What about adding this into .gitignore file? 
such as in this way:
`xcuserdata/`

2024-03-11 05:32 UTC, jonibekbekmuratov commented on OnlineCinema/OnlineCinema/Modules/Home/HomeAssembler.swift
> +class HomeAssembler {
What about using `enum` instead of `class` for assembler?
```suggestion
enum HomeAssembler {
```

2024-03-13 09:18 UTC, leoru commented on OnlineCinema/OnlineCinema/Modules/Home/HomeIntent.swift
> +final class HomeIntent {
Полагаю, для того чтобы это все было быстро переиспользуемое с меньшим количеством кода в новых модулях, интенты должны быть generic и впускать в себя generic model и generic data

2024-03-15 04:04 UTC, merged